### ISSUE TITLE
Alt is not being set to images

### ISSUE THREAD

**Issue by davidgomezcol** [oesah/djangocms_slick_slider#3]
* djangocms_slick_slider version: 0.7.2
* Django version: 1.11
* Python version: 3.6
* Operating System: AWS linux

### Description

I'm setting Alt and Name to images, but they're not being set on.

What i spect to happen, is that the Alt needs to be set on the <img class="" style="opacity: 1;" src="https://mysite/thresa.jpg__2000x2000_q85_subsampling-2_upscale.jpg">

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by oesah** [comment]
Hey @davidgomezcol 

Has been implemented in `v.1.0.0`. It uses the default alt text from the django-filer field.

**Comment by oesah** [comment]
@davidgomezcol Try out the latest version `1.0.4`.
