### ISSUE TITLE
Null Slider Images

### ISSUE THREAD

**Issue by riquedev** [oesah/djangocms_slick_slider#6]
* djangocms_slick_slider version: Default (1.8.0)
* Django version: 3.1.12
* Python version: 3.9.4
* Operating System: Windows 10

### Description
Images are showing up as "unknown" and null/None attributes

### What I Did
I just put the plugin in and uploaded the images, one detail, I'm using django-storages[google] but even before I put it I was having this problem.

![image](https://user-images.githubusercontent.com/18220248/124148667-3bd0ef80-da66-11eb-8029-02a2d66ae747.png)

**Comment by oesah** [comment]
Hmm, this is usually due to some problems with your MEDIA settings. I had this once in another project with AWS hosted media files. Can you please check your configuration? What happens, when you simply add a `{{ my_image }}` in your template, does it have a proper URL?

**Comment by riquedev** [comment]
> Hmm, this is usually due to some problems with your MEDIA settings. I had this once in another project with AWS hosted media files. Can you please check your configuration? What happens, when you simply add a `{{ my_image }}` in your template, does it have a proper URL?


When I present just the {{image}} instance (using the package's internal template) it returns the image name.

A partial of my settings.py

```python
STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(DATA_DIR, 'media')
STATIC_ROOT = os.path.join(DATA_DIR, 'static')

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'absite', 'static'),
)

SITE_ID = 1

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'absite', 'templates'),
            os.path.join(BASE_DIR, 'automotive_header', 'templates'),
        ],
        'OPTIONS': {
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.media',
                'django.template.context_processors.csrf',
                'django.template.context_processors.tz',
                'sekizai.context_processors.sekizai',
                'django.template.context_processors.static',
                'cms.context_processors.cms_settings'
            ],
            'loaders': [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader'
            ],
        },
    },
]

MIDDLEWARE = [
    'cms.middleware.utils.ApphookReloadMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'cms.middleware.user.CurrentUserMiddleware',
    'cms.middleware.page.CurrentPageMiddleware',
    'cms.middleware.toolbar.ToolbarMiddleware',
    'cms.middleware.language.LanguageCookieMiddleware'
]

INSTALLED_APPS = [
    'djangocms_admin_style',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.admin',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'django.contrib.staticfiles',
    'django.contrib.messages',
    'cms',
    'menus',
    'sekizai',
    'treebeard',
    'djangocms_text_ckeditor',
    'filer',
    "meta",
    'easy_thumbnails',
    'aldryn_apphooks_config',
    'parler',
    'taggit',
    'taggit_autosuggest',
    'sortedm2m',
    'djangocms_blog',
    "djangocms_page_meta",
    'djangocms_bootstrap4',
    'djangocms_bootstrap4.contrib.bootstrap4_alerts',
    'djangocms_bootstrap4.contrib.bootstrap4_badge',
    'djangocms_bootstrap4.contrib.bootstrap4_card',
    'djangocms_bootstrap4.contrib.bootstrap4_carousel',
    'djangocms_bootstrap4.contrib.bootstrap4_collapse',
    'djangocms_bootstrap4.contrib.bootstrap4_content',
    'djangocms_bootstrap4.contrib.bootstrap4_grid',
    'djangocms_bootstrap4.contrib.bootstrap4_jumbotron',
    'djangocms_bootstrap4.contrib.bootstrap4_link',
    'djangocms_bootstrap4.contrib.bootstrap4_listgroup',
    'djangocms_bootstrap4.contrib.bootstrap4_media',
    'djangocms_bootstrap4.contrib.bootstrap4_picture',
    'djangocms_bootstrap4.contrib.bootstrap4_tabs',
    'djangocms_bootstrap4.contrib.bootstrap4_utilities',
    "aldryn_search",
    'djangocms_file',
    'djangocms_icon',
    'djangocms_link',
    'djangocms_picture',
    'djangocms_style',
    'djangocms_googlemap',
    'djangocms_video',
    'djangocms_slick_slider.apps.DjangocmsSlickSliderConfig',
    "automotive_header",
    "automotive_nav",
    'absite'
]


X_FRAME_OPTIONS = 'SAMEORIGIN'

CMS_PERMISSION = True

CMS_PLACEHOLDER_CONF = {}

THUMBNAIL_PROCESSORS = (
    'easy_thumbnails.processors.colorspace',
    'easy_thumbnails.processors.autocrop',
    'filer.thumbnail_processors.scale_and_crop_with_subject_location',
    'easy_thumbnails.processors.filters'
)

DEFAULT_FILE_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'
STATICFILES_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'
GS_BUCKET_NAME = '#hide#'
GS_LOCATION = "#hide#"
GS_PROJECT_ID = '#hide#'
GS_DEFAULT_ACL = '#hide#'
GS_FILE_OVERWRITE = True
GCS_USE_UNSIGNED_URLS = True

````
![image](https://user-images.githubusercontent.com/18220248/124150027-8a32be00-da67-11eb-9070-eb5dca780dca.png)

**Comment by oesah** [comment]
Yeah it looks like some configuration in your settings is messed up. You can see in https://github.com/oesah/djangocms_slick_slider/blob/master/djangocms_slick_slider/templates/djangocms_slick_slider/base.html how it render the images. It first tries to make a thumbnail. If the url of the image is faulty, the thumbnail creation fails and then it return the `(unknown)` property. Unfortunately, it's not an issue with the code in this repo. 

I use this lib with a client of mine, where we host our images on AWS S3 and that one works. You can try to create a thumbnail with your images using `{% thumbnail image.image image.full_width_dimensions upscale=True as thumb %}` to check if it works.

**Comment by riquedev** [comment]
> Yeah it looks like some configuration in your settings is messed up. You can see in https://github.com/oesah/djangocms_slick_slider/blob/master/djangocms_slick_slider/templates/djangocms_slick_slider/base.html how it render the images. It first tries to make a thumbnail. If the url of the image is faulty, the thumbnail creation fails and then it return the `(unknown)` property. Unfortunately, it's not an issue with the code in this repo.
> 
> I use this lib with a client of mine, where we host our images on AWS S3 and that one works. You can try to create a thumbnail with your images using `{% thumbnail image.image image.full_width_dimensions upscale=True as thumb %}` to check if it works.

I think I found something, in fact it looks like I'm having some problem with the image instance.

The full_width_dimensions parameter is always returning "NonexNone", I'll check if I can do something about it.

Thank you for your attention.

**Comment by riquedev** [comment]
Problem solved!
In fact it was my configuration fault, I had set the "Full width" but I hadn't informed the maximum size for the height and width of the images.
I apologize and once again thank you for your attention. ✨
